### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'other'

### ISSUE THREAD

**Issue by cyriacbijun** [Kanjirito/simple-manga-downloader#25]
@Kanjirito this is a wonderful library and have found it very useful. But, after the version 1.12.0, I believe you brought about some changes to support MangaDex. The following error is always shown irrespective of `down` or `conf` command
```
 Traceback (most recent call last):
  File "/home/username/.local/bin/SMD", line 5, in <module>
    from simple_manga_downloader.SMD import main
  File "/home/username/.local/lib/python3.8/site-packages/simple_manga_downloader/SMD.py", line 10, in <module>
    from . import __version__, modules, utils
  File "/home/username/.local/lib/python3.8/site-packages/simple_manga_downloader/modules/__init__.py", line 6, in <module>
    from .mangadex_org import Mangadex
  File "/home/username/.local/lib/python3.8/site-packages/simple_manga_downloader/modules/mangadex_org.py", line 77, in <module>
    class Mangadex(BaseManga):
  File "/home/username/.local/lib/python3.8/site-packages/simple_manga_downloader/modules/mangadex_org.py", line 81, in Mangadex
    session.mount("https://", ReporterLimiter(session))
  File "/home/username/.local/lib/python3.8/site-packages/simple_manga_downloader/modules/mangadex_org.py", line 48, in __init__
    super().__init__(5, 0, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/simple_manga_downloader/modules/mangadex_org.py", line 24, in __init__
    r = Retry(
TypeError: __init__() got an unexpected keyword argument 'other'
```
It might be a trivial bug, sincerely requesting your help

**Comment by Kanjirito** [comment]
The issue isn't with the downloader itself but your `urllib3` version. I did not realize that a feature I'm using was introduced fairly recently in version 1.26.0. A solution to this problem should be to just upgrade `urllib3`. You can do that through pip with `pip install --user --upgrade urllib3`. I'll mark the required version in the installation requirements.
